const model = {
   
   //#region PokemonData
    pokemonData: [
        {id: '001', pokemon:'Bulbasaur',   type1: 'Grass',     type2: 'Poison',   species: 'Seed Pokemon',          height: '0.7m',  weight: '6.9 kg',   img: '<img src="./pokemon/001bulbasaur.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '002', pokemon:'Ivysaur',     type1: 'Grass',     type2: 'Poison',   species: 'Seed Pokemon',          height: '1.0 m', weight: '13.0 kg',  img: '<img src="./pokemon/002ivysaur.jpg"    style="width: 150px; height: 150px;">',  },
        {id: '003', pokemon:'Venusaur',    type1: 'Grass',     type2: 'Poison',   species: 'Seed Pokemon',          height: '2.0 m', weight: '100 kg',   img: '<img src="./pokemon/003venusaur.jpg"   style="width: 150px; height: 150px;">',  },
        {id: '004', pokemon:'Charmander',  type1: 'Fire',      type2: '',         species: 'Lizard Pokemon',        height: '0.6 m', weight: '8.5 kg',   img: '<img src="./pokemon/004charmander.jpg" style="width: 150px; height: 150px;">',  },
        {id: '005', pokemon:'Charmeleon',  type1: 'Fire',      type2: '',         species: 'Flame Pokemon',         height: '1.1 m', weight: '19.0 kg',  img: '<img src="./pokemon/005charmeleon.jpg" style="width: 150px; height: 150px;">',  },
        {id: '006', pokemon:'Charizard',   type1: 'Fire',      type2: 'Flying',   species: 'Flame Pokemon',         height: '1.7 m', weight: '90.5 kg',  img: '<img src="./pokemon/006charizard.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '007', pokemon:'Squirtle',    type1: 'Water',     type2: '',         species: 'Tiny turtle Pokemon',   height: '0.5 m', weight: '9.0 kg',   img: '<img src="./pokemon/007squirtle.jpg"   style="width: 150px; height: 150px;">',  },
        {id: '008', pokemon:'Wartortle',   type1: 'Water',     type2: '',         species: 'Turtle Pokemon',        height: '1.0 m', weight: '22.5 kg',  img: '<img src="./pokemon/008wartortle.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '009', pokemon:'Blastoise',   type1: 'Water',     type2: '',         species: 'Shellfish Pokemon',     height: '1.6 m', weight: '85.5 kg',  img: '<img src="./pokemon/009blastoise.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '010', pokemon:'Caterpie',    type1: 'Bug',       type2: '',         species: '',     height: '', weight: '',  img: '<img src="./pokemon/010caterpie.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '011', pokemon:'Metapod',     type1: 'Bug',       type2: '',         species: '',     height: '', weight: '',  img: '<img src="./pokemon/011Metapod.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '012', pokemon:'Butterfree',  type1: 'Bug',       type2: 'Flying',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/012Butterfree.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '013', pokemon:'Weedle',      type1: 'Bug',       type2: 'Poison',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/013Weedle.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '014', pokemon:'Kakuna',      type1: 'Bug',       type2: 'Poison',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/014Kakuna.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '015', pokemon:'Beedrill',    type1: 'Bug',       type2: 'Poison',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/015Beedrill.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '016', pokemon:'Pidgey',      type1: 'Normal',    type2: 'Flying',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/016Pidgey.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '017', pokemon:'Pidgeotto',   type1: 'Normal',    type2: 'Flying',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/017Pidgeotto.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '018', pokemon:'Pidgeot',     type1: 'Normal',    type2: 'Flying',   species: '',     height: '', weight: '',  img: '<img src="./pokemon/018Pidgeot.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '019', pokemon:'Rattata',     type1: 'Normal',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/019Rattata.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '020', pokemon:'Raticate',    type1: 'Normal',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/020Raticate.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '021', pokemon:'Spearow',     type1: 'Normal',    type2: 'Flying', species: '',     height: '', weight: '',  img: '<img src="./pokemon/021Spearow.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '022', pokemon:'Fearow',      type1: 'Normal',    type2: 'Flying', species: '',     height: '', weight: '',  img: '<img src="./pokemon/022Fearow.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '023', pokemon:'Ekans',       type1: 'Poison',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/023Ekans.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '024', pokemon:'Arbok',       type1: 'Poison',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/024Arbok.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '025', pokemon:'Pikachu',     type1: 'Electric',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/025Pikachu.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '026', pokemon:'Raichu',      type1: 'Electric',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/026Raichu.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '027', pokemon:'Sandshrew',   type1: 'Ground',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/027Sandshrew.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '028', pokemon:'Sandslash',   type1: 'Ground',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/028Sandslash.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '029', pokemon:'Nidoran♀',    type1: 'Poison',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/029Nidoran-f.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '030', pokemon:'Nidorina',    type1: 'Poison',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/030Nidorina.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '031', pokemon:'Nidoqueen',   type1: 'Poison',    type2: 'Ground', species: '',     height: '', weight: '',  img: '<img src="./pokemon/031Nidoqueen.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '032', pokemon:'Nidoran♂',    type1: 'Poison',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/032Nidoran-m.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '033', pokemon:'Nidorino',    type1: 'Poison',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/033Nidorino.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '034', pokemon:'Nidoking',    type1: 'Poison',    type2: 'Ground', species: '',     height: '', weight: '',  img: '<img src="./pokemon/034Nidoking.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '035', pokemon:'Clefairy',    type1: 'Fairy',     type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/035Clefairy.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '036', pokemon:'Clefable',    type1: 'Fairy',     type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/036Clefable.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '037', pokemon:'Vulpix',      type1: 'Fire',      type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/037Vulpix.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '038', pokemon:'Ninetales',   type1: 'Fire',      type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/038Ninetales.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '039', pokemon:'Jigglypuff',  type1: 'Normal',    type2: 'Fairy', species: '',     height: '', weight: '',  img: '<img src="./pokemon/039Jigglypuff.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '040', pokemon:'Wigglytuff',  type1: 'Normal',    type2: 'Fairy', species: '',     height: '', weight: '',  img: '<img src="./pokemon/040Wigglytuff.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '041', pokemon:'Zubat',       type1: 'Poison',    type2: 'Flying', species: '',     height: '', weight: '',  img: '<img src="./pokemon/041Zubat.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '042', pokemon:'Golbat',      type1: 'Poison',    type2: 'Flying', species: '',     height: '', weight: '',  img: '<img src="./pokemon/042Golbat.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '043', pokemon:'Oddish',      type1: 'Grass',     type2: 'Poison', species: '',     height: '', weight: '',  img: '<img src="./pokemon/043Oddish.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '044', pokemon:'Gloom',       type1: 'Grass',     type2: 'Poison', species: '',     height: '', weight: '',  img: '<img src="./pokemon/044Gloom.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '045', pokemon:'Vileplume',   type1: 'Grass',     type2: 'Poison', species: '',     height: '', weight: '',  img: '<img src="./pokemon/045Vileplume.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '046', pokemon: 'Paras',      type1: 'Bug',       type2: 'Grass', species: '',     height: '', weight: '',  img: '<img src="./pokemon/046Paras.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '047', pokemon: 'Parasect',   type1: 'Bug',       type2: 'Grass', species: '',     height: '', weight: '',  img: '<img src="./pokemon/047Parasect.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '048', pokemon: 'Venonat',    type1: 'Bug',       type2: 'Poison', species: '',     height: '', weight: '',  img: '<img src="./pokemon/048Venonat.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '049', pokemon: 'Venomoth',   type1: 'Bug',       type2: 'Poison', species: '',     height: '', weight: '',  img: '<img src="./pokemon/049Venomoth.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '050', pokemon: 'Diglett',    type1: 'Ground',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/050Diglett.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '051', pokemon: 'Dugtrio',    type1: 'Ground',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/051Dugtrio.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '052', pokemon: 'Meowth',     type1: 'Normal',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/052Meowth.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '053', pokemon: 'Persian',    type1: 'Normal',    type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/053Persian.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '054', pokemon: 'Psyduck',    type1: 'Water',     type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/054Psyduck.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '055', pokemon: 'Golduck',    type1: 'Water',     type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/055Golduck.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '056', pokemon: 'Mankey ',    type1: 'Fighting',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/056Mankey.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '057', pokemon: 'Primeape',   type1: 'Fighting',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/057Primeape.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '058', pokemon: 'Growlithe',  type1: 'Fire',      type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/058Growlithe.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '059', pokemon: 'Arcanine',   type1: 'Fire',      type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/059Arcanine.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '060', pokemon: 'Poliwag',    type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/060Poliwag.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '061', pokemon: 'Poliwhirl',  type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/061Poliwhirl.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '062', pokemon: 'Poliwrath',  type1: '',  type2: 'Fighting', species: '',     height: '', weight: '',  img: '<img src="./pokemon/062Poliwrath.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '063', pokemon: 'Abra',       type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/063Abra.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '064', pokemon: 'Kadabra',    type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/064Kadabra.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '065', pokemon: 'Alakazam',   type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/065Alakazam.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '066', pokemon: 'Machop',     type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/066Machop.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '067', pokemon: 'Machoke',    type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/067Machoke.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '068', pokemon: 'Machamp',    type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/068Machamp.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '069', pokemon: 'Bellsprout', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/069Bellsprout.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '070', pokemon: 'Weepinbell', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/070Weepinbell.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '071', pokemon: 'Victreebel', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/071Victreebel.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '072', pokemon: 'Tentacool',  type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/072Tentacool.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '073', pokemon: 'Tentacruel', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/073Tentacruel.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '074', pokemon: 'Geodude',    type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/074Geodude.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '075', pokemon: 'Graveler',   type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/075Graveler.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '076', pokemon: 'Golem',      type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/076Golem.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '077', pokemon: 'Ponyta    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/077Ponyta.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '078', pokemon: 'Rapidash  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/078Rapidash.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '079', pokemon: 'Slowpoke  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/079Slowpoke.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '080', pokemon: 'Slowbro   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/080Slowbro.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '081', pokemon: 'Magnemite ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/081Magnemite.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '082', pokemon: 'Magneton  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/082Magneton.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '083', pokemon: 'Farfetchd ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/083Farfetchd.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '084', pokemon: 'Doduo     ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/084Doduo.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '085', pokemon: 'Dodrio    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/085Dodrio.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '086', pokemon: 'Seel      ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/086Seel.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '087', pokemon: 'Dewgong   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/087Dewgong.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '088', pokemon: 'Grimer    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/088Grimer.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '089', pokemon: 'Muk       ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/089Muk.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '090', pokemon: 'Shellder  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/090Shellder.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '091', pokemon: 'Cloyster  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/091Cloyster.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '092', pokemon: 'Gastly    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/092Gastly.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '093', pokemon: 'Haunter   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/093Haunter.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '094', pokemon: 'Gengar    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/094Gengar.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '095', pokemon: 'Onix      ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/095Onix.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '096', pokemon: 'Drowzee   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/096Drowzee.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '097', pokemon: 'Hypno     ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/097Hypno.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '098', pokemon: 'Krabby    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/098Krabby.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '099', pokemon: 'Kingler   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/099Kingler.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '100', pokemon: 'Voltorb   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/100Voltorb.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '101', pokemon: 'Electrode ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/101Electrode.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '102', pokemon: 'Exeggcute ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/102Exeggcute.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '103', pokemon: 'Exeggutor ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/103Exeggutor.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '104', pokemon: 'Cubone    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/104Cubone.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '105', pokemon: 'Marowak   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/105Marowak.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '106', pokemon: 'Hitmonlee ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/106Hitmonlee.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '107', pokemon: 'Hitmonchan', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/107Hitmonchan.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '108', pokemon: 'Lickitung ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/108Lickitung.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '109', pokemon: 'Koffing   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/109Koffing.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '110', pokemon: 'Weezing   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/110Weezing.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '111', pokemon: 'Rhyhorn   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/111Rhyhorn.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '112', pokemon: 'Rhydon    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/112Rhydon.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '113', pokemon: 'Chansey   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/113Chansey.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '114', pokemon: 'Tangela   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/114Tangela.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '115', pokemon: 'Kangaskhan', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/115Kangaskhan.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '116', pokemon: 'Horsea    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/116Horsea.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '117', pokemon: 'Seadra    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/117Seadra.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '118', pokemon: 'Goldeen   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/118Goldeen.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '119', pokemon: 'Seaking   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/119Seaking.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '120', pokemon: 'Staryu    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/120Staryu.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '121', pokemon: 'Starmie   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/121Starmie.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '122', pokemon: 'Mr. Mime  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/122Mr-mime.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '123', pokemon: 'Scyther   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/123Scyther.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '124', pokemon: 'Jynx      ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/124Jynx.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '125', pokemon: 'Electabuzz', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/125Electabuzz.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '126', pokemon: 'Magmar    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/126Magmar.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '127', pokemon: 'Pinsir    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/127Pinsir.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '128', pokemon: 'Tauros    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/128Tauros.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '129', pokemon: 'Magikarp  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/129Magikarp.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '130', pokemon: 'Gyarados  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/130Gyarados.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '131', pokemon: 'Lapras    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/131Lapras.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '132', pokemon: 'Ditto     ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/132Ditto.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '133', pokemon: 'Eevee     ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/133Eevee.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '134', pokemon: 'Vaporeon  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/134Vaporeon.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '135', pokemon: 'Jolteon   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/135Jolteon.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '136', pokemon: 'Flareon   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/136Flareon.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '137', pokemon: 'Porygon   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/137Porygon.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '138', pokemon: 'Omanyte   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/138Omanyte.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '139', pokemon: 'Omastar   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/139Omastar.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '140', pokemon: 'Kabuto    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/140Kabuto.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '141', pokemon: 'Kabutops  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/141Kabutops.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '142', pokemon: 'Aerodactyl', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/142Aerodactyl.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '143', pokemon: 'Snorlax   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/143Snorlax.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '144', pokemon: 'Articuno  ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/144Articuno.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '145', pokemon: 'Zapdos    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/145Zapdos.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '146', pokemon: 'Moltres   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/146Moltres.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '147', pokemon: 'Dratini   ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/147Dratini.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '148', pokemon: 'Dragonair ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/148Dragonair.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '149', pokemon: 'Dragonite ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/149Dragonite.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '150', pokemon: 'Mewtwo    ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/150Mewtwo.jpg"  style="width: 150px; height: 150px;">',  },
        {id: '151', pokemon: 'Mew       ', type1: '',  type2: '', species: '',     height: '', weight: '',  img: '<img src="./pokemon/151Mew.jpg"  style="width: 150px; height: 150px;">',  },
    ],
//#endregion

};